# Generated by Django 4.0.1 on 2022-01-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='koeran_name',
            new_name='korean_name',
        ),
    ]
